config/routes.rb
Rails.application.routes.draw do

  # devise_for :merchants
  get 'errors/not_found'
  get 'errors/internal_server_error'
  post 'uploader' => 'blogs#uploader'
  post '/ckeditor/pictures' , :to => 'blogs#ckeditor_picture',:defaults => { :format => 'json' }
  resources :booking_dates
  
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users'
  
  devise_for :merchants, path: 'merchants', controllers: { sessions: "merchants/sessions", registrations: "merchants/registrations"}

  devise_scope :merchants do
    get '/merchants/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :merchant do
    get '/merchants/pertner_sign_up_with_email' ,:to => 'merchants/registrations#pertner_sign_up_with_email'
  end

  get 'merchants_status_approved' => 'application#merchants_status_approved'
  
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post] 
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post] 



  match '/paytm_payment' => 'payment_systems#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'payment_systems#verify_payment', via: [:post]

  namespace :ecofnb do
    get 'index'
    get 'ecofriendly'
    get 'filter_search_stay'
    get 'about'
    get 'all_stay_homes'
    get 'founder_message' 
    get 'help'
    get 'support'
  end
  
  namespace :profile do
    get 'guest_profile'
  end

namespace :blogs do
    get 'short_blog'
  end

  root 'ecofnb#index'

  resources :contacts, only: [:new ,:create]
  resources :blogs, only: [:index,:show]

 resources :galleries ,only: [:index]
 namespace :galleries do
    get 'video'
    get 'merchant'
  end
  
 resources :stay ,only:[:show] do
  member do
    get 'bookings/new'
  end
 end


 resources :bookings, only: [:new, :create] do 
    collection do
      get :search_rooms
      # route for checkig available_rooms
      get :available_rooms
    end
  end

  resources :stay, only: [] do
    member do
      get 'bookings/new'
    end
    # Using booking resources
    resources :bookings, only: [:new, :create] do 
      collection do
        get :search_rooms
        # route for checkig available_rooms
        get :available_rooms
      end
    end
  end

 # resources :rating_reviews
 resources :faqs, only: [:index]
 resources :merchant

  get 'orders' => 'merchant#booking_order'
  get 'my_account' => 'merchant#profile'

 resources :stay_homes do
  member do
    resources :rating_reviews
    get :stay_status_approved
  end
 end

 scope :path => '/stay_homes/:stay_home_id' do
  resources :rooms, :controller => :rooms do
  end
end
# scope :path => '/stay_homes/:stay_home_id' do
  resources :room_categories #, :controller => :room_categories do
  # end
# end
 controller 'ecofnb' do
   # get 'beverage_locations/new' => 'beverage_locations#new'
   get '/Stay/:stay_id' => 'ecofnb#stay_category'
   get 'signup_with_email' =>'ecofnb#signup_with_email'
end

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
match "/422", :to => "errors#unacceptable" , :via => :all
end

app/views/shared/_footer.html.erb
 <footer id="footer-main" class="container-fluid no-left-padding no-right-padding footer-main">
   <!-- Top Footer -->
   <div class="container-fluid no-left-padding no-right-padding top-footer vijay">
      <!-- Container -->
      <div class="container">
         <!-- Row -->
         <div class="row">
            <!-- Widget About -->
            <div class="col-md-4 col-sm-6 col-xs-6">

              <aside class="widget widget_contact">
                  <h3 class="widget-title">Contact us</h3>
                  <p><i class="fa fa-map-marker"></i>Jagannath Complex, First Floor, Nainital Road Haldwani</p>
                  <p><i class="fa fa-mobile"></i><a href="tel:+917078877002"> (+91) 7078877002</a></p>
                  <p><i class="fa fa-envelope"></i><a href="mailto:youremail@mail.com">info@ecofnb.com</a></p>
                  <p><i class="fa fa-internet-explorer"></i><a target="_blank" href="http://www.ecofnb.com">www.ecofnb.com</a></p>
              </aside>

                  <aside class="widget widget_social">
                     <ul>
                        <li><a href="https://www.facebook.com/Ecofnb-1591258727642130/?modal=admin_todo_tour" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/ecofnb" target="_blank"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.instagram.com/ecofnb/" target="_blank"><i class="fa fa-instagram" ></i></a></li>
                        <li>
                           <a href="https://www.youtube.com/channel/UC8rgXc5jzlLGIZyDbg2vYBg
                              "target="_blank"><i class="fa fa-youtube"></i></a>
                        </li>
                     </ul>
                  </aside>
              
            </div>
            <!-- Widget About /- -->
            <!-- Widget Links -->
            <div class="col-md-4 col-sm-6 col-xs-6">
              <aside class="widget widget_latestposts">
                  <h3 class="widget-title">Latest Blog</h3>
                  <%@latest_post.each do |r_post|%>
                     <div class="latest-content">
                        <a href="<%=blog_path(r_post)%>" title="<%= r_post.title %>"><i><img src="<%=r_post.image.url(:thumb)%>" class="wp-post-image" alt="blog-1" style="width: 90 ;height: 40px;"></i></a>
                        <h5><a class="tc_dark tc_green_h" title="<%= r_post.title %>" href="<%=blog_path(r_post)%>"><%= r_post.title %> </a></h5>
                     </div>
                  <%end%>
               </aside>

            </div>
            <!-- Widget Links /- -->
            <!-- Widget Latest Post -->
            <div class="col-md-4 col-sm-6 col-xs-6">
               
            </div>
            <!-- Widget Latest Post -->
            <!-- Widget Tags -->
            <div class="col-md-3 col-sm-6 col-xs-6">
               <aside class="widget widget_latestposts">
                  <h3 class="widget-title">Latest Partners</h3>
                  <% @latest_stay.each do |latest_stay| %>
                  <div class="latest-content">
                     <a href="<%= stay_path(latest_stay)%>" title="<%latest_stay.stay_title%>"><i><img src="<%=latest_stay.stay_images.first.stay_image.url%>" class="wp-post-image" alt="blog-1" style="width: 90 ;height: 40px;"></i></a>
                        <h5><a class="tc_dark tc_green_h" title="<%= latest_stay.stay_title %>" href="<%= stay_path(latest_stay)%>"><%= latest_stay.stay_title %> </a></h5>
                   </div>
                     <% end %>
               </aside>
            </div>
            <!-- Widget Tags /- -->
         </div>
         <!-- Row /- -->
      </div>
      <!-- Container /- -->
   </div>
   <!-- Top Footer -->
   <!-- Bottom Footer -->
   <div class="container-fluid bottom-footer">
      <!-- Container -->
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-7">
            <div class="footer-links text-center">
              <ul>
                <li><a href="/ecofnb/about">About us</a> |</li>
                <li><a href="/ecofnb/founder_message">Founder Message</a> |</li>
                <li><%= link_to "Terms & Conditions", asset_path("term_condition.pdf") %> |</li>
                <li><%= link_to "Privacy Policy", asset_path("PRIVACY_POLICY.pdf") %> |</li>
                <li><a href="<%= new_contact_path%>">Contact us</a> |</li>
                <li><a href="<%= faqs_path%>">Faqs</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="powered-by pull-right">
             <p><span class="design-by">Design By</span> <a href="http://www.ryientsoft.com/" target="_blank">RyientSoft Technology</a></p> 
          </div>
          </div>
        </div>
         <!--Start of Tawk.to Script-->
         <!-- <script type="text/javascript">
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
            var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
            s1.async=true;
            s1.src='https://embed.tawk.to/5c57c53e7cf662208c93e8b9/default';
            s1.charset='UTF-8';
            s1.setAttribute('crossorigin','*');
            s0.parentNode.insertBefore(s1,s0);
            })();
         </script>
 -->
         <!--End of Tawk.to Script-->
      </div>
      <!-- Container -->
   </div>
   <!-- Bottom Footer /- -->
</footer>
<!-- Footer Main /- -->
<!-- JQuery v1.12.4 -->
<!-- Library - Js -->
<style type="text/css">
    .footer-bitt{
      float: right;
    /* padding-bottom: 17px; */
     letter-spacing: 1.4px;
    padding-top: 15px;
    color: #fff
   }
   .footer-bitt  a{
      color: #01c26e!important;
      letter-spacing: 1.4px;
   }

</style>
<style>
/*.vijay {
  background-image: url("<%#=asset_path('footer-bg1.jpg')%>");
  width: 100%;
  height: auto;
  background-size: 100% 100%;
  background-position: center center;
  opacity: 1;
  background-color: transparent;
  background-repeat: no-repeat;
}*/

.footer-links ul {
    list-style-type: none;
}

.footer-links ul li {
    display: inline-block;
        color: #fff;

}
.footer-links ul li a
 {
  color: #01c26e;
  letter-spacing: 0.5px;
  
 }
 span.design-by {
    color: #fff;
    letter-spacing: 0.5px;
}
.powered-by p a {
    color: #01c26e;
    letter-spacing: 0.5px;
}
.powered-by p
{
  padding: 0 10px;
  
}
</style>

app/views/shared/_header.html.erb
<header class="header_s header_s1">
   <!-- SidePanel -->
   <div id="slidepanel">
      <!-- Top Header -->
      <div class="container-fluid no-right-padding no-left-padding top-header brd_color_green">
         <!-- Container -->
         <div class="container mng-width">
            <div class="top-left tcp_gray">
               <p><i class="fa fa-home"></i>Jagannath Complex, First Floor, Nainital Road, Haldwani</p>
               <p><i class="fa fa-phone tc_gray"></i> 7078877002</p>
              
            </div>
            <div class="top-right">
              <% if merchant_signed_in? %>
                <p><i class="fa fa-user tc_dark"></i><a class="tc_dark tc_green_h" href="<%=merchant_index_path%>" title="Signup">Dashboard</a></p>
                      <p><i class="fa fa-key tc_dark"></i><%= link_to "Sign out Partner", destroy_merchant_session_path,:class => "tc_dark tc_green_h", :method => :get %>
                      <% else %>
                        <% if user_signed_in? %>
                        <div class="dropdown">
                          <!-- <button onclick="myFunction()" class="fa fa-user">Dropdown</button> -->
                          <button style="font-size:20px"><i class="fa fa-user" onclick="myFunction()"></i></button>
                       <!--   <i class="fa fa-user-circle" onclick="myFunction()"></i> -->
                          <div id="myDropdown" class="dropdown-content">
                            <a href="/bookings">My Bookings</a>
                            <a href="/profile/guest_profile">My Profile</a>
                            <a href="/ecofnb/support">24x7 support</a>
                            <a href="<%=faqs_path%>">FAQ</a>
                           <%= link_to "Logout", destroy_user_session_path, :method => :get %>
                          </div>
                        </div>
                     <!--  <p><i class="fa fa-key tc_dark"></i> --><%#= link_to "Sign out Guest", destroy_user_session_path,:class => "tc_dark tc_green_h", :method => :delete %>
                    <% else %>
                     <p><i class="fa fa-user tc_dark"></i><a class="tc_dark tc_green_h" href="<%=new_merchant_session_path%>" title="Partner Login">Partner</a></p>
                         <p><i class="fa fa-key tc_dark"></i><a class="tc_dark tc_green_h" href="<%= new_user_session_path%>" title="Guest Login">Guest</a></p>
                       
               <% end %>
               <% end %>
               <!-- <ul>
                  <li><a class="tc_dark tc_sugar_h bg_green_h" href="https://www.facebook.com/Ecofnb-1591258727642130/?modal=admin_todo_tour" target="_blank"><i class="fa fa-facebook"></i></a></li>
                  <li><a class="tc_dark tc_sugar_h bg_green_h" target="_blank" href="https://twitter.com/Ecofnb1"><i class="fa fa-twitter"></i></a></li>
                  <li><a class="tc_dark tc_sugar_h bg_green_h" target="_blank" href="https://plus.google.com/u/1/113106467864886857517"><i class="fa fa-google-plus"></i></a></li>
                  <li><a class="tc_dark tc_sugar_h bg_green_h" target="_blank" href="https://www.facebook.com/eco.fnb.98/about?section=overview&info_surface=intro_card&lst=100030543525272%3A100030543525272%3A1543393825
                     "><i class="fa fa-instagram"></i></a></li>
                  <li><a class="tc_dark tc_sugar_h bg_green_h" target="_blank" href="https://www.youtube.com/channel/UC8rgXc5jzlLGIZyDbg2vYBg"><i class="fa fa-youtube"></i></a></li>
               </ul> -->


            
            </div>
         </div>
         <!-- Container /- -->
      </div>
      <!-- Top Header /- -->
   </div>
   <!-- SidePanel /- -->
   <!-- Ownavigation -->
   <nav class="navbar ownavigation bg_black menu_color">
      <!-- Container -->
      <div class="container1">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="<%= asset_path("ecofnblogo/logo121.png")%>" alt="logo" height="180" width="180"></a>
         </div>
         <div class="donation-btn">
<!--             <a class="bg_green tc_white tc_green_h bg_white_h" href="/ecofnb/all_stay_homes" title="Book Now">Book Now</a> -->
         </div>
         <div class="search">
            <a href="javascript:void(0);" id="search" title="Search"><i class="fa fa-search"></i></a>
         </div>
         <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <li class="active"><a href="/">home</a></li>
               <li class=""><a href="/ecofnb/about">about us</a></li>
               <li class=""><a href="/ecofnb/founder_message">founder Message</a></li>

               <li class="dropdown">
                  <a href="#" class="" role="button" aria-haspopup="true" aria-expanded="false">stays</a>
                  <i class="ddl-switch fa fa-angle-down"></i>
                  <ul class="dropdown-menu">
                  <% if @stay_categories.any? %>   
                     <%@stay_categories.each do |s_categories|%>
                        <li><a href="/Stay/<%=s_categories.slug%>"><%=s_categories.try(:name)%></a></li>
                        <!-- <li><a href="/galleries/video">Video</a></li> -->
                        <% end -%>
                  <% end -%>
               </ul>
               </li>
               
               <!-- <li class=""><a href="/ecofnb/homestay">stay</a></li> -->
               <li class="dropdown">
                  <a href="#" class="" role="button" aria-haspopup="true" aria-expanded="false">Gallery</a>
                  <i class="ddl-switch fa fa-angle-down"></i>
                  <ul class="dropdown-menu">
                     <li><a href="/galleries">Gallery</a></li>
                     <li><a href="/galleries/video">Video</a></li>
                  </ul>
               </li>
               <li><a href="<%=blogs_path%>">Blog</a></li>
               <!-- <li class="dropdown">
                  <a href="#" class="" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                  <i class="ddl-switch fa fa-angle-down"></i>
                  <ul class="dropdown-menu">
                     <li><a href="<%=blogs_path%>">Blog Post</a></li>
                  </ul>
               </li> -->
               <li class=""><a href="<%= new_contact_path%>">contact us</a></li>
            </ul>
         </div>
         <div id="loginpanel" class="desktop-hide">
            <div class="right" id="toggle">
               <a id="slideit" href="#slidepanel"><i class="fo-icons fa fa-inbox"></i></a>
               <a id="closeit" href="#slidepanel"><i class="fo-icons fa fa-close"></i></a>
            </div>
         </div>
         <!-- Search Box -->
         <div class="search-box">
            <span><i class="icon_close"></i></span>
            <!-- <input type="text" class="form-control" placeholder="Enter a keyword and press enter..." /> -->

              <%= render 'ecofnb/search'%>
         </div>
         <!-- Search Box /- -->
      </div>
      <!-- Container /- -->
   </nav>
   <!-- Ownavigation /- -->
</header>
<!-- Header Section /- -->

<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  div = document.getElementById("myDropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>

app/views/shared/_main_link.html.erb
<aside class="widget widget_categories scrollpoint sp-effect3">
    <div class="widget-title">
        <h3 class="tc_dark">Links</h3>
    </div>
    <ul>
        <li><a class="tc_dark tc_green_h" href="/"><i class="fa fa-home"></i>Home</a></li>
        <li><a class="tc_dark tc_green_h" href="/ecofnb/about"><i class="fa fa-adn"></i>About</a></li>
        <li><a class="tc_dark tc_green_h" href="/ecofnb/founder_message"><i class="fa fa-user"></i>Founder Message</a></li>
        <li><a class="tc_dark tc_green_h" href="/galleries"><i class="fa fa-photo"></i>Gallery</a></li>
        <li><a class="tc_dark tc_green_h" href="<%= new_contact_path%>"><i class="fa fa-phone"></i>Contact</a></li>

    </ul>
</aside>

app/views/shared/_message.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible show" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button"><span aria-hidden="true"> ×</span></button>
    <strong><%= flash[:success] %></strong>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning alert-dismissible show" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button"><span aria-hidden="true"> ×</span></button>
    <strong><%= flash[:warning] %></strong>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible show" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button"><span aria-hidden="true"> ×</span></button>
    <strong><%= flash[:error] %></strong>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible show" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button"><span aria-hidden="true"> ×</span></button>
    <strong><%= flash[:notice] %></strong>
<% end %>