config/routes.rb
Rails.application.routes.draw do

  # devise_for :merchants
  get 'errors/not_found'
  get 'errors/internal_server_error'
  post 'uploader' => 'blogs#uploader'
  post '/ckeditor/pictures' , :to => 'blogs#ckeditor_picture',:defaults => { :format => 'json' }
  resources :booking_dates
  
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users'
  
  devise_for :merchants, path: 'merchants', controllers: { sessions: "merchants/sessions", registrations: "merchants/registrations"}

  devise_scope :merchants do
    get '/merchants/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :merchant do
    get '/merchants/pertner_sign_up_with_email' ,:to => 'merchants/registrations#pertner_sign_up_with_email'
  end

  get 'merchants_status_approved' => 'application#merchants_status_approved'
  
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post] 
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post] 



  match '/paytm_payment' => 'payment_systems#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'payment_systems#verify_payment', via: [:post]

  namespace :ecofnb do
    get 'index'
    get 'ecofriendly'
    get 'filter_search_stay'
    get 'about'
    get 'all_stay_homes'
    get 'founder_message' 
    get 'help'
    get 'support'
  end
  
  namespace :profile do
    get 'guest_profile'
  end

namespace :blogs do
    get 'short_blog'
  end

  root 'ecofnb#index'

  resources :contacts, only: [:new ,:create]
  resources :blogs, only: [:index,:show]

 resources :galleries ,only: [:index]
 namespace :galleries do
    get 'video'
    get 'merchant'
  end
  
 resources :stay ,only:[:show] do
  member do
    get 'bookings/new'
  end
 end


 resources :bookings, only: [:new, :create] do 
    collection do
      get :search_rooms
      # route for checkig available_rooms
      get :available_rooms
    end
  end

  resources :stay, only: [] do
    member do
      get 'bookings/new'
    end
    # Using booking resources
    resources :bookings, only: [:new, :create] do 
      collection do
        get :search_rooms
        # route for checkig available_rooms
        get :available_rooms
      end
    end
  end

 # resources :rating_reviews
 resources :faqs, only: [:index]
 resources :merchant

  get 'orders' => 'merchant#booking_order'
  get 'my_account' => 'merchant#profile'

 resources :stay_homes do
  member do
    resources :rating_reviews
    get :stay_status_approved
  end
 end

 scope :path => '/stay_homes/:stay_home_id' do
  resources :rooms, :controller => :rooms do
  end
end
# scope :path => '/stay_homes/:stay_home_id' do
  resources :room_categories #, :controller => :room_categories do
  # end
# end
 controller 'ecofnb' do
   # get 'beverage_locations/new' => 'beverage_locations#new'
   get '/Stay/:stay_id' => 'ecofnb#stay_category'
   get 'signup_with_email' =>'ecofnb#signup_with_email'
end

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
match "/422", :to => "errors#unacceptable" , :via => :all
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :stay_home
  belongs_to :room_category
	has_many :booking_rooms
  has_many :bookings, through: :booking_rooms

  validates :name, :stay_home_id,:presence => true
	scope :available?, -> (start_date, last_date=nil) {
   available_rooms(start_date, last_date).present? }
  # Scope for finding all the available rooms
  # scope :available_rooms, -> (room_id, room_category_id, start_date, last_date=nil) {
  #   last_date = start_date if last_date.nil?
  #   # Fetching all the booked rooms in the particular date range
  #   hotel_rooms = includes(:bookings=>:booking_dates).where("booking_dates.reserved_date": start_date..last_date)
  #   # Filtering all the booked rooms and finding out the available rooms for particular
  #   where.not(id: hotel_rooms.map(&:id))
  # }
################room_id room_categopry_id ###############
  def self.available_rooms(start_date=nil,last_date=nil,room_id=nil , room_category_id=nil)
		# byebug
		last_date = start_date if last_date.nil?
    # Fetching all the booked rooms in the particular date range
    hotel_rooms = includes(:bookings =>:booking_dates).where("booking_dates.reserved_date": start_date..last_date)
    # Filtering all the booked rooms and finding out the available rooms for particular
    where.not(id: hotel_rooms.map(&:id))
		# byebug
  end
# def self.available_rooms( room_id=nil,room_categopry_id=nil,start_date, last_date=nil)
#     last_date = start_date if last_date.nil?
#     # Fetching all the booked rooms in the particular date range
#     hotel_rooms = includes(:bookings =>:booking_dates).where("booking_dates.reserved_date": start_date..last_date)
#     # Filtering all the booked rooms and finding out the available rooms for particular
#     where.not(id: hotel_rooms.map(&:id))
#   end

  # Checking if particular room is avaliable or not
  def available?(start_date, last_date=nil)
    last_date = start_date if last_date.nil?
    # we are also able to search for one day booking
    # dates we are taking as yyyy/mm/dd
    # example available("2016/10/9")
    # example available("2016/10/2","2016/10/9")
    # searching bookings using start_date and last_date date range
    bookings.joins(:booking_dates).where("booking_dates.reserved_date": start_date..last_date).blank?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < InheritedResources::Base
  before_action :find_stay_id, only: [:edit, :update, :destroy]
   layout 'dashboard'

    def index
      @rooms = current_merchant.stay_homes.where(id: StayHome.find(params[:stay_home_id])).last.rooms
    end

	def new
    # byebug
    @room_categories = StayHome.find_by(id: params[:stay_home_id]).room_categories
		@room = Room.new
	end

  def edit
    @room = Room.find(params[:id])
    @room_categories = RoomCategory.all
  end

  def create
   @room = Room.new(room_params)
    @stay = StayHome.find(params[:room][:stay_home_id]).id if params[:room][:stay_home_id].present?
     @room.stay_home_id = @stay
      respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_url}
        flash[:success] = 'home stay room was successfully created.'
        format.json { render :show, status: :created, location:  @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_url(stay_home_id: @room.stay_home_id), notice: 'home stay room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end



  private

    def room_params
      params.require(:room).permit(:name, :stay_home_id, :room_category_id)
    end

    def find_stay_id
      @room = Room.find(params[:id])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= render 'rooms/room_layout'%>
<div class="card">
   <!-- SignUp Form -->
   <div class="container-fluid no-left-padding no-right-padding signup-section">
   <!-- Container -->
   <div class="container">
      <div class="row">
         <div class="col-md-offset-1 col-md-10">
            <div class="signup-form">
                <%= form_with(model: room, local: true) do |form| %>
                  <% if room.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

                      <ul>
                      <% room.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="field">
                    <%= form.label :Room_Number %>
                    <%= form.text_field :name, class: "form-control" %>
                  </div>
                  <div class="field">
                    <%= form.label :Room_Category %>
                    <%#= byebug %>
                    <%= form.select :room_category_id, @room_categories.collect { |p| [ p.category_name, p.id ] }, { }, { class: "form-control" }%>
                  </div>

                  <%= form.hidden_field :stay_home_id, :value => params[:stay_home_id] %>
                  <div class="actions">
                   <div class="form-group col-md-12 tc_dark">
                  <div class="form-group col-md-12 signup-btn">
                    <%= form.submit 'Submit', class: "btn" %>
                  </div>
                  </div>
                  </div>
                <% end %>
                </div>
             </div>
            </div>
         </div>
      </div>
</div>
         

app/views/rooms/_room_layout.html.erb
<div class="container-fluid no-left-padding no-right-padding page-banner gallery-masonry-banner">
    
  <div class="container">
    <h3 class="tc_white"></h3>
    <ol class="breadcrumb">
      <li><a class="tc_white tc_white_h" href="#"></a></li>
      <!-- <li class="active tc_white"></li> -->
    </ol>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'rooms/room_layout'%>
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'rooms/room_layout'%>
<div class="card">
   <!-- SignUp Form -->
   <div class="container-fluid no-left-padding no-right-padding signup-section">
   <!-- Container -->
   <div class="container">
      <div class="row">
         <div class="col-md-offset-1 col-md-12">
            <div class="signup-form">
               <table class="table table-hover datatable table-bordered display responsive no-wrap">
                <thead>
                  <tr>
                    <th>Room Name/Number</th>
                    <th>Room Category</th>
                    <th>Stay</th>
                    <th> Show</th>
                    <th> Edit </th>
                    <th> Delete </th>
                  </tr>
                </thead>

                <tbody>
                  <% @rooms.each do |room| %>
                    <tr>
                      <td><%= room.name %></td>
                      <td><%= room.room_category.category_name %></td>
                      <td><%= room.stay_home.stay_name%></td>
                      <td><%= link_to 'Show', room_path(room.stay_home.id,room.id) %></td>
                      <td><%= link_to 'Edit', edit_room_path(room.stay_home.id,room.id) %></td>
                      <td><%= link_to 'Destroy', room_path(room.stay_home.id,room.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
               <div class="form-group col-md-12 tc_dark">
                  <div class="form-group col-md-12 signup-btn">
                   <%= link_to 'New Room', new_room_path, class: "btn bg_green tc_white tc_green_h bg_white_h" %>
                  </div>
               </div>
            </div>
          </div>
        </div>
     </div>
   </div>

   </div>
<script type="text/javascript">
  $('.datatable').DataTable({
  });
</script>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= render 'rooms/room_layout'%>

<div class="card">
   <!-- SignUp Form -->
   <div class="container-fluid no-left-padding no-right-padding signup-section">
   <!-- Container -->
   <div class="container">
      <div class="row">
         <div class="col-md-offset-1 col-md-10">
			<p>
			  <strong>Room Name/Number:</strong>
			  <%= @room.name %>
			</p>

			<p>
			  <strong>Room Category:</strong>
			  <%= @room.room_category.category_name %>
			</p>

			<p>
			  <strong>Stay:</strong>
			  <%= StayHome.find(@room.stay_home_id).try(:stay_name) %>
			</p>

			<td><%= link_to 'Edit', edit_room_path(@room.stay_home.id,@room.id) %></td> |
			<%= link_to 'Back', rooms_path %>
		</div>
	</div>
</div>
</div>
</div>