config/routes.rb
Rails.application.routes.draw do

  # devise_for :merchants
  get 'errors/not_found'
  get 'errors/internal_server_error'
  post 'uploader' => 'blogs#uploader'
  post '/ckeditor/pictures' , :to => 'blogs#ckeditor_picture',:defaults => { :format => 'json' }
  resources :booking_dates
  
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users'
  
  devise_for :merchants, path: 'merchants', controllers: { sessions: "merchants/sessions", registrations: "merchants/registrations"}

  devise_scope :merchants do
    get '/merchants/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :merchant do
    get '/merchants/pertner_sign_up_with_email' ,:to => 'merchants/registrations#pertner_sign_up_with_email'
  end

  get 'merchants_status_approved' => 'application#merchants_status_approved'
  
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post] 
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post] 



  match '/paytm_payment' => 'payment_systems#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'payment_systems#verify_payment', via: [:post]

  namespace :ecofnb do
    get 'index'
    get 'ecofriendly'
    get 'filter_search_stay'
    get 'about'
    get 'all_stay_homes'
    get 'founder_message' 
    get 'help'
    get 'support'
  end
  
  namespace :profile do
    get 'guest_profile'
  end

namespace :blogs do
    get 'short_blog'
  end

  root 'ecofnb#index'

  resources :contacts, only: [:new ,:create]
  resources :blogs, only: [:index,:show]

 resources :galleries ,only: [:index]
 namespace :galleries do
    get 'video'
    get 'merchant'
  end
  
 resources :stay ,only:[:show] do
  member do
    get 'bookings/new'
  end
 end


 resources :bookings, only: [:new, :create] do 
    collection do
      get :search_rooms
      # route for checkig available_rooms
      get :available_rooms
    end
  end

  resources :stay, only: [] do
    member do
      get 'bookings/new'
    end
    # Using booking resources
    resources :bookings, only: [:new, :create] do 
      collection do
        get :search_rooms
        # route for checkig available_rooms
        get :available_rooms
      end
    end
  end

 # resources :rating_reviews
 resources :faqs, only: [:index]
 resources :merchant

  get 'orders' => 'merchant#booking_order'
  get 'my_account' => 'merchant#profile'

 resources :stay_homes do
  member do
    resources :rating_reviews
    get :stay_status_approved
  end
 end

 scope :path => '/stay_homes/:stay_home_id' do
  resources :rooms, :controller => :rooms do
  end
end
# scope :path => '/stay_homes/:stay_home_id' do
  resources :room_categories #, :controller => :room_categories do
  # end
# end
 controller 'ecofnb' do
   # get 'beverage_locations/new' => 'beverage_locations#new'
   get '/Stay/:stay_id' => 'ecofnb#stay_category'
   get 'signup_with_email' =>'ecofnb#signup_with_email'
end

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
match "/422", :to => "errors#unacceptable" , :via => :all
end

app/models/room_category.rb
class RoomCategory < ApplicationRecord
	has_many :rooms
	belongs_to :stay_home
	has_many :stay_images,as: :immageable, dependent: :destroy
    accepts_nested_attributes_for :stay_images,  :allow_destroy => true,:reject_if => :all_blank

end

app/controllers/room_categories_controller.rb
class RoomCategoriesController < ApplicationController
  before_action :set_room_category, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'

  # GET /room_categories
  # GET /room_categories.json
  def index
    @room_categories = RoomCategory.all
  end

  def show
  end

  # GET /room_categories/new
  def new
    # byebug
    @room_category = RoomCategory.new
    @room_category.stay_images
  end

  # GET /room_categories/1/edit
  def edit
  end

  # POST /room_categories
  # POST /room_categories.json
  def create
    @room_category = RoomCategory.new(room_category_params)
    # @room_category.stay_images
    respond_to do |format|
      if @room_category.save
        format.html { redirect_to @room_category, notice: 'Room category was successfully created.' }
        format.json { render :show, status: :created, location: @room_category }
      else
        format.html { render :new }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_categories/1
  # PATCH/PUT /room_categories/1.json
  def update
    respond_to do |format|
      if @room_category.update(room_category_params)
        format.html { redirect_to @room_category, notice: 'Room category was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_category }
      else
        format.html { render :edit }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_categories/1
  # DELETE /room_categories/1.json
  def destroy
    @room_category.destroy
    respond_to do |format|
      format.html { redirect_to room_categories_url, notice: 'Room category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_category
      @room_category = RoomCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_category_params
      params.require(:room_category).permit(:category_name, :category_price, :stay_home_id ,stay_images_attributes: [:id, :stay_image,:_destroy])
    end
end

app/helpers/room_categories_helper.rb
module RoomCategoriesHelper
end

app/views/room_categories/_form.html.erb
<%= nested_form_for room_category, local: true do |form| %>
  <% if room_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_category.errors.count, "error") %> prohibited this room_category from being saved:</h2>

      <ul>
      <% room_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
        <%= form.label :Category_Name %>
        <%= form.text_field :category_name, class: "form-control" %>
    </div>
    <div class="field">
        <%= form.label :Category_Price %>
        <%= form.text_field :category_price, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :Stay_Home %>
      <%= form.select :stay_home_id, current_merchant.stay_homes.all.collect { |p| [ p.stay_name, p.id ] }, { }, { class: "form-control" }%>
    </div>
    <br/>
    <div class="col-md-6">
                     <%= form.fields_for :stay_images do |task| %>
                     <%= task.file_field :stay_image, class: "form-control" %>
                     <% if task.object.stay_image and task.object.stay_image.file %>
                     <%= image_tag task.object.stay_image.url ,size:"100x100"%>
                     <%end%><br/>
                     <%= task.link_to_remove "Remove this Images" %><br/>
                     <% end %>
                     <%= form.link_to_add "Add Stay Images", :stay_images %>
                  </div>
    <div class="actions">
     <div class="form-group col-md-12 tc_dark">
    <div class="form-group col-md-12 signup-btn">
      <%= form.submit 'Create', class: "btn" %>
    </div>
<% end %>
<br><br><br><br>

app/views/room_categories/edit.html.erb
<h1>Editing Room Category</h1>

<%= render 'form', room_category: @room_category %>

<%= link_to 'Show', @room_category %> |
<%= link_to 'Back', room_categories_path %>

app/views/room_categories/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h3>Room Categories</h3>
<div class="card">
   <!-- SignUp Form -->
   <div class="container-fluid no-left-padding no-right-padding signup-section">
   <!-- Container -->
   <div class="container">
      <div class="row">
         <div class="col-md-offset-1 col-md-12">
            <div class="signup-form">
               <table class="table table-hover datatable table-bordered display responsive no-wrap">
                <thead>
                  <tr>
                    <th>Category Name</th>
                    <th>Category </th>
                    <th>Stay</th>
                    <!-- <th> Show</th> -->
                   <!--  <th> Edit </th> -->
                   <!--  <th> Delete </th> -->
                  </tr>
                </thead>

                <tbody>
                  <% @room_categories.each do |room_category| %>
                    <tr>
                      <td><%= room_category.category_name %></td>
                      <td><%= room_category.category_price %></td>
                      <td><%= room_category.stay_home.stay_name%></td>
                      <!-- <td><%#= link_to 'Show', room_category %></td> -->
                      <!-- <td><%#= link_to 'Edit', edit_room_category_path(room_category) %></td> -->
                      <!-- <td><%#= link_to 'Destroy', room_category, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                    </tr>
                  <% end %>
                </tbody>
              </table>
               <div class="form-group col-md-12 tc_dark">
                  <div class="form-group col-md-12 signup-btn">
                   <%= link_to 'New Room Category', new_room_category_path, class: "btn bg_green tc_white tc_green_h bg_white_h" %>
                  </div>
               </div>
            </div>
          </div>
        </div>
     </div>
   </div>
  </div>
  <script type="text/javascript">
  $('.datatable').DataTable({
  });
</script>

app/views/room_categories/new.html.erb
<br><br>
<h1>New Room Category</h1>

<%= render 'form', room_category: @room_category %>

<%= link_to 'Back', room_categories_path %>

app/views/room_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_room_category_path(@room_category) %> |
<%= link_to 'Back', room_categories_path %>