config/routes.rb
Rails.application.routes.draw do

  # devise_for :merchants
  get 'errors/not_found'
  get 'errors/internal_server_error'
  post 'uploader' => 'blogs#uploader'
  post '/ckeditor/pictures' , :to => 'blogs#ckeditor_picture',:defaults => { :format => 'json' }
  resources :booking_dates
  
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users'
  
  devise_for :merchants, path: 'merchants', controllers: { sessions: "merchants/sessions", registrations: "merchants/registrations"}

  devise_scope :merchants do
    get '/merchants/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :merchant do
    get '/merchants/pertner_sign_up_with_email' ,:to => 'merchants/registrations#pertner_sign_up_with_email'
  end

  get 'merchants_status_approved' => 'application#merchants_status_approved'
  
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post] 
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post] 



  match '/paytm_payment' => 'payment_systems#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'payment_systems#verify_payment', via: [:post]

  namespace :ecofnb do
    get 'index'
    get 'ecofriendly'
    get 'filter_search_stay'
    get 'about'
    get 'all_stay_homes'
    get 'founder_message' 
    get 'help'
    get 'support'
  end
  
  namespace :profile do
    get 'guest_profile'
  end

namespace :blogs do
    get 'short_blog'
  end

  root 'ecofnb#index'

  resources :contacts, only: [:new ,:create]
  resources :blogs, only: [:index,:show]

 resources :galleries ,only: [:index]
 namespace :galleries do
    get 'video'
    get 'merchant'
  end
  
 resources :stay ,only:[:show] do
  member do
    get 'bookings/new'
  end
 end


 resources :bookings, only: [:new, :create] do 
    collection do
      get :search_rooms
      # route for checkig available_rooms
      get :available_rooms
    end
  end

  resources :stay, only: [] do
    member do
      get 'bookings/new'
    end
    # Using booking resources
    resources :bookings, only: [:new, :create] do 
      collection do
        get :search_rooms
        # route for checkig available_rooms
        get :available_rooms
      end
    end
  end

 # resources :rating_reviews
 resources :faqs, only: [:index]
 resources :merchant

  get 'orders' => 'merchant#booking_order'
  get 'my_account' => 'merchant#profile'

 resources :stay_homes do
  member do
    resources :rating_reviews
    get :stay_status_approved
  end
 end

 scope :path => '/stay_homes/:stay_home_id' do
  resources :rooms, :controller => :rooms do
  end
end
# scope :path => '/stay_homes/:stay_home_id' do
  resources :room_categories #, :controller => :room_categories do
  # end
# end
 controller 'ecofnb' do
   # get 'beverage_locations/new' => 'beverage_locations#new'
   get '/Stay/:stay_id' => 'ecofnb#stay_category'
   get 'signup_with_email' =>'ecofnb#signup_with_email'
end

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
match "/422", :to => "errors#unacceptable" , :via => :all
end

app/controllers/ecofnb_controller.rb
class EcofnbController < ApplicationController

  def index
    @videos = Video.all.where(active: true)
    @galleries = Gallery.all.order('updated_at DESC')
    @gallery_types = PhotogalleryType.all
    # byebug
    @homestays = StayHome.all.where(status:"approved").order('updated_at DESC').limit(6)
    @homestay_left = @homestays.limit(3)
    @homestay_right = @homestays.where.not(id: @homestay_left).limit(3)
    @h_stay_last = StayHome.all.order('updated_at DESC').last
    end

  def all_stay_homes    
     
     if params[:search_parameters].present?
        @stay_homes = search(params[:search_parameters])
    else
      
      @stay_homes = StayHome.all.where(status: 2)
    end
  end

  def about
    @about_us = AboutU.all.last
  end

  def founder_message
    @founder_message = FounderMessage.all.last
  end

  def ecofriendly
  end

  def stay_category
      @stay_category = Stay.find(params[:stay_id]) 
      # byebug
      @homestays = @stay_category.stay_homes.approved
  end

  def search(params)
    ###########rajeet ##############
    @search =StayHome.search(params).star_rating(params).stay_type(params)
    if params[:price].present?  
      min = params["price"].split('-').first
      max = params["price"].split('-').last
      @price_search_data=@search.joins(:room_categories).where("room_categories.category_price": min..max).uniq 
      return @price_search_data
  end 
  return @search
    #################rajeet###########
  end

  def signup_with_email

  end

end

app/views/ecofnb/_blank.html.erb
<div class="col-sm-9">
         <main class="site-main">
              <div class="container-fluid no-left-padding no-right-padding gallery-main gallery-masonry">
              <div class="row gallery-list">
                <div class="col-md-12 gallery-list">
                  <div class="gallery-slide">
                    <%# <div class="row"> %>
                      <%# <div class="col-md-4 bg-transparent"> %>
                        <%# <h3 style="text-align: center;"> We Are  </h3> %>
                        <img src="https://res.cloudinary.com/testing-aman-react/image/upload/v1584545427/ecofnb/dns1hpwjbv5ygptl6lkh.jpg" width="100%"/>
                      <%# </div>   %>
                    <%# </div> %>
                  </div>
              </div>
            </div>
            </div>
        </main>
  </div>
  <!-- <div class="col-md-1"></div> -->

app/views/ecofnb/_filter_stay.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="row">
        <div class="col-md-12 filter-by-block md-margin-bottom-60">
          <div class="panel-group" id="accordion">
            <div class="dropdown">
              <label class="aman" style="font-family:Verdana;">Stay Categories</label>
              <%= select_tag "stay_type", options_from_collection_for_select(Stay.all, 'id', 'name', params[:search_parameters][:stay_type]), class: "form-control dropdown" %>
            </div>
          </div>
        </div>
        <!-- <div class="col-md-12 filter-by-block md-margin-bottom-60">
          <div class="panel-group" >
            <div class="panel panel-default">
              <div class="panel-heading">
                <h2 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    <label style="font-family:Verdana;">Stay Star Rating</label>
                    <i class="fa fa-angle-down"></i>
                  </a>
                </h2>
              </div>
              <div class="">
                <div class="">
                  <ul class="list-unstyled checkbox-list">
                    <li>
                      <input type="checkbox" onclick="star_rating('5')">
                         <span class="fa fa-star checked"></span>
                         <span class="fa fa-star checked"></span>
                         <span class="fa fa-star checked"></span>
                         <span class="fa fa-star checked"></span>
                         <span class="fa fa-star checked"></span>
                    </li>
                    <li>
                      <input type="checkbox" id="4rating" onclick="star_rating('4')">
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                    </li>
                    <li>
                      <input type="checkbox" id="3rating" onclick="star_rating('3')">
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                    </li>
                    <li>
                      <input type="checkbox" id="2rating" onclick="star_rating('2')">
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                    </li>
                    <li>
                      <input type="checkbox" id="1rating" onclick="star_rating('1')">
                        <span class="fa fa-star checked"></span>
                    </li>                 
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  select#stay_type {
    margin-left: 10px;
    padding: 3px;
    height: 31px;
    width: 150px;
    font-size: 19px;
    text-transform: uppercase;
    margin-top: -4px;
}
label.aman {
    margin-left: 12px;

}
</style>

app/views/ecofnb/_popular_stay.html.erb
<div id="portfolio" class="portfolio-area area-padding fix scrollpoint sp-effect3">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="section-headline text-center">
             <div class="section-heading">
                <h1>Popular Stays in Uttarakhand</h1>
                <div class="divider"><hr/></div>
             </div>
            </div>
          </div>
        </div>
        <div class="row awesome-project-content">
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 design development">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay4.jpeg')%>" alt="" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="<%=asset_path('popular_stay4.jpeg')%>">
                      <h4>Simba Cafe & Restaurant</h4>
                      <span>Binsar, Uttarakhand</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 photo">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay5.jpeg')%>" alt="<%=asset_path('popular_stay5.jpeg')%>" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="<%=asset_path('popular_stay5.jpeg')%>">
                      <h4>Book Now</h4>
                      <%# <span>Photosho</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 design">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay6.jpeg')%>" alt="<%=asset_path('popular_stay6.jpeg')%>" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="<%=asset_path('popular_stay6.jpeg')%>">
                      <h4>Book Now</h4>
                      <%# <span>Web Design</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 photo development">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay7.jpeg')%>" alt="<%=asset_path('popular_stay7.jpeg')%>" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="<%=asset_path('popular_stay7.jpeg')%>">
                      <h4>Book Now</h4>
                      <%# <span>Web design</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 development">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay.jpg')%>" alt="" /></a>
                <div class="add-actions text-center text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="/">
                      <h4>Book Now</h4>
                      <%# <span>Web Development</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 design photo">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay1.jpg')%>" alt="" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="/">
                      <h4>Book Now</h4>
                      <%# <span>Photoshop</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 design photo">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="<%=asset_path('popular_stay2.jpg')%>" alt="" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="/">
                      <h4>Book Now</h4>
                      <%# <span>Photoshop</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
          <!-- single-awesome-project start -->
          <div class="col-md-3 col-sm-3 col-xs-12 design photo">
            <div class="single-awesome-project">
              <div class="awesome-img">
                <a href="#"><img class="popular-image" src="https://www.hindwatch.in/wp-content/uploads/2016/11/view-more.png" alt="" /></a>
                <div class="add-actions text-center">
                  <div class="project-dec">
                    <a class="venobox" data-gall="myGallery" href="<%=asset_path('popular_stay3.png')%>">
                      <h4>Veiw More<br/> +</h4>
                      <%# <span>Photoshop</span> %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- single-awesome-project end -->
        </div>
      </div>
    </div><!-- End Portfolio Section -->

    <style>
    </style>
<script>
$(window).on("load", function() {
    var $container = $('.awesome-project-content');
    $container.isotope({
      filter: '*',
      animationOptions: {
        duration: 750,
        easing: 'linear',
        queue: false
      }
    });
    var pro_menu = $('.project-menu li a');
    pro_menu.on("click", function() {
      var pro_menu_active = $('.project-menu li a.active');
      pro_menu_active.removeClass('active');
      $(this).addClass('active');
      var selector = $(this).attr('data-filter');
      $container.isotope({
        filter: selector,
        animationOptions: {
          duration: 750,
          easing: 'linear',
          queue: false
        }
      });
      return false;
    });

  });</script>

app/views/ecofnb/all_stay_homes.html.erb
<br>
<br>
<%# byebug %>
<%#= render 'search'%>
<%#if params[:search_parameters].present?%>  
<style type="text/css">
  .main-container {
    margin-top: 200px !important;
}
</style>  

<div class="row"> 
   <div class="col-md-2"> 
     <%= render 'filter_stay' %>
   </div>
   <% if @stay_homes.present? %>  
   <div class="col-sm-9">
         <main class="site-main">
              <% if flash[:alert] %>
               <div class="alert"><%= flash[:alert] %></div>
              <% end %>
              <div class="container-fluid no-left-padding no-right-padding gallery-main gallery-masonry">
              <div class="row gallery-list">
                <div class="col-md-12 gallery-list">
                <% @stay_homes.each do |homestay|%> 
                    <div class="gallery-slide">
                  <div class="row">
                     <div class="col-md-4">
                        <div class="gallery-box environment">
                          <div class="gallery-content">
                            <i><a href="<%= stay_path(homestay)%>"><img src="<%= homestay.image_select%>" alt="<%= homestay.stay_name%>" /></a></i>
                            <div class="gallery-detail">
                          <a class="zoom" href="<%= homestay.image_select%>"><i class="fa fa-picture-o"></i></a>
                          <a href="<%=stay_path(homestay)%>"><i class="fa fa-link"></i></a>
                          </div>
                        </div>
                        </div>
                      </div>
                        <div class="col-md-8">
                          <div class="row">
                              <div class="col-md-8">
                              <div class="left_blog">
                                  <% if homestay.avg_rating==0.0 %>
                                   <% (1 .. 5.to_i).each do |t|%>
                                   <span class="fa fa-star-empty"></span>
                                   <%end %>
                                   <%else%>
                                   <% (1 .. homestay.avg_rating.to_i).each do |t|%>
                                   <span class="fa fa-star checked"></span>
                                   <% end %>
                                   <% if homestay.avg_rating.to_s.split('.')[1].to_i > 0 %>
                                   <span class="fa fa-star-half abc"></span>
                                   <% end %>
                                   <%# byebug %>
                                  <!--  <a class="bg_green tc_white tc_green_h bg_white_h" href="#">Stay</a> -->
                                  <% end %>
                                  <div>
                                    <h3 class="tc_dark">
                                      <a class="tc_dark" href="<%= stay_path(homestay)%>"><%= homestay.stay_name%>
                                      </a>
                                    </h3>
                                    <h4 class="category"><%= homestay.stay.name%></h4>
                                  </div>
                                  <div><span class="tc_gray"><%= homestay.address%></span></div><br>
                                  <div><span class="small aman">LANDMARK:&nbsp;&nbsp;<%=homestay.try(:location_description)%></span></div><br>
                                  <!-- <a data-toggle='popover' title="<%= homestay.try(:cancellation_policy) %>" href="#">cancellation policy</a>  -->
                                  <div class="hotel-services">
                                    <ul>
                                    <li class="small">
                                      <span>
                                        <% homestay.facilities.each do |icon|%>
                                        
                                      <i title="<%= icon.name%>" class="<%= icon.feature_icon %>"></i>
                                    <%end%></span>
                                      </i>
                                    </li>
                                    </ul>
                                  </div>
                                  </div>
                               </div>
                               
                               <div class="col-md-4">
                               <div class="right_blog">
                                  <div class="review-rate texdat-right text-right">
                                  <a class="bg_green tc_white tc_green_h bg_white_h"><%= homestay.avg_rating %>/5</a>
                                  </div>
                                  <div class="reviews-count text-right">
                                   <span class="total-review-txt"><a><%= homestay.rating_reviews.count %> Review</a></span>
                                   </div>
                                  
                                  <div class="text-right">
                                  <strike><i class="fa fa-rupee"></i><%= ((homestay.room_categories.first.category_price)*25)/100+homestay.room_categories.first.category_price %></strike>
                                <div class="large"><i class="fa fa-rupee"></i><%= homestay.room_categories.first.category_price %></div><samll> per room/ per night</samll>
                                </div>
                                <div class="view-more destination-btn text-right">
                                   <a href="<%= new_stay_booking_path(homestay)%>" class="btn btn-success">RESERVE ROOM</a>
                                </div>                       
                              <div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <%end%>   
            </div>
          </div>
        </div>
      </main>
  </div>
  <div class="col-md-1"></div>
</div>
<% else %>

<%= render 'blank' %>
<% end %>
  
<style type="text/css">
  .review-rate.texdat-right.text-right{
    font-size: 20px;
    color: #2c5506;
    font-weight: 700;
  }
samll {
    font-size: 15px;
}
  span.total-review-txt {
    font-size: 17px;
}
a.tc_dark {
  color: #2c5406 !important;
  text-transform: uppercase;
}
h4.category {
  font-size: 16px !important;
  text-transform: uppercase;
  margin-left: 5px;
  color: #2c5506;
}
a.btn.btn-success {
    background-color: #2c5506;
}
a.btn.btn-success:hover {
    background-color: #fff;
    color: #2c5506;
}
span.tc_gray {
  font-size: 15px !important;
  margin-left: 5px !important;
  text-align: left !important;
  color: #2c5506 !important;
}
span.small.aman {
  font-size: 14px;
  font-weight: 600;
  margin-left: 5px;
  text-transform: uppercase;
  color: #2c5506 !important;
}

.gallery-content img {
  margin: 20px;
  width: 90%;
  float: left;
  height: 190px;
  min-height: 190px;
}
.checked {
  color: orange;
}
.abc{
  color: orange;
}
.gallery-slide {
  width: 100%;
  float: left;
  box-shadow: 0.5px 0.5px 5px 0px #4d504e;
  margin: 5px 0;
  border-radius: 4px;
}
.gallery-slide p
{
  padding: 10px;
}
.gallery-content img {
  border-radius: 8px;
}
.hotel-services ul {
    list-style-type: none;
    padding: 0;
}

.hotel-services ul li {
    display: inline-block;
    margin-right: 5px;
}

.hotel-services ul li i {
    padding: 5px 10px;
    font-size: 25px !important;
    background-color: #2c5406;
    border-radius: 5px; 
    color: #fff;
}
.hotel-services ul li i:hover {
    padding: 5px 10px;
    font-size: 25px !important;
    background-color: #b6d896;
    border-radius: 5px; 
    color: #2c5406;
}
.popover {
  max-width: none;
}
.gallery-slide .destination-btn a {
    padding: 6px 6px;
}

.gallery-slide .destination-btn {
    margin: 15px 0;
    text-align: right;
}
.review-rate a {
    border-radius: 4px;
    padding: 5px;
}
.right_blog {
    float: left;
    width: 100%;
    padding: 20px;
    border-left: 1px solid #dbdbdb;
}
.left_blog
{
  float: left;
    width: 100%;
    padding: 20px;
}
span.fa.fa-star.checked {
    font-size: 20px;
}
.reviews-count {
    width: 100%;
    float: left;
    padding: 6px 0px 0 0;
}
.large {
    font-size: 30px;
    font-weight: 700;
}
</style>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/hot-sneaks/jquery-ui.css" />
<!-- <script src="http://code.jquery.com/jquery-2.1.3.js"></script>
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script> -->
<script type="text/javascript">
    function toggleChevron(e) {
    $(e.target)
        .prev('.panel-heading')
        .find("i.indicator")
        .toggleClass('fa-caret-down fa-caret-right');
  }
</script>

<script type="text/javascript">
  function star_rating(amount) {
    var amounts = []
       if ($('#my-star-rating').val() != "") {
        amounts.push($('#my-star-rating').val())
       }
      if ($('#my-star-rating').val().includes(amount)) {
        
        amounts = amounts[0].split(",")
         var index = amounts.indexOf(amount);
        if (index > -1) {
          amounts.splice(index, 1);
        }
      }else{
        amounts.push(amount)
      }
      
       $('#my-star-rating').val(amounts);

       $('#search-form').submit();
}

    var param_star_rating = '<%= star_rating_values(params) %>'.split(",");
       if (param_star_rating.includes('1')) {
        $('#1rating').prop('checked', true);
       }
       if (param_star_rating.includes('2')) {
        $('#2rating').prop('checked', true);
       }
       if (param_star_rating.includes('3')) {
        $('#3rating').prop('checked', true);
       }
       if (param_star_rating.includes('4')) {
        $('#4rating').prop('checked', true);
       }
       if (param_star_rating.includes('5')) {
        $('#5rating').prop('checked', true);
       }
</script>

<!-- <script type="text/javascript">
  var  autocomplete;
  function initAutocomplete() {
    autocomplete = new google.maps.places.Autocomplete((document.getElementById('autocomplete')),
        {types: ['geocode']});

  }
  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({
          center: geolocation,
          radius: position.coords.accuracy
        });
        autocomplete.setBounds(circle.getBounds());
      });
    }
  }
</script> -->

<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNcD7L1bPn2xaFFtU6BUhXAUU_1FdNZQI&signed_in=true&libraries=places&callback=initAutocomplete" async defer></script>
</style> -->
<script type="text/javascript">
  $(function () {
        $("#stay_type").change(function () {
            var selectedText = $(this).find("option:selected").val();
            var selectedValue = $(this).val();
            // console.log(selectedValue)
        $( "#type_stay" ).val(selectedValue);
        $( "#stay_type" ).val(selectedValue);
        $('#search-form').submit();
        });
    });
</script>
<script>
      $(document).ready(function() {
      $( "#mySlider" ).slider({
        range: true,
        min: 1,
        max: 5000,
        values: [ <%= price_values(params).present? ? price_values(params).split('-')[0] : 0 %>, <%= price_values(params).present? ? price_values(params).split('-')[1] : 10000 %>],
        slide: function( event, ui ) {
       $( "#price" ).val( "" + ui.values[ 0 ] + " - " + ui.values[ 1 ] );
       },

         stop: function( event, ui ) {
       $( "#price_range" ).val( "" + ui.values[ 0 ] + "-" + ui.values[ 1 ] );
       $('#search-form').submit();
       }
    });
    $( "#price" ).val( "" + $( "#mySlider" ).slider( "values", 0 ) +
             " - " + $( "#mySlider" ).slider( "values", 1 ) );
        
      });
  </script>

app/views/ecofnb/index.html.erb
<!--Slider Start-->
<%= render 'ecofnb/slider1' %>
<!--Slider End--> 
<%= render 'ecofnb/search' %>
<%#= render 'stay/search1' %>
<!-- Stay_category Start-->

<%= render 'ecofnb/popular_stay' %>

<!--Stay_category End -->
<!--About Section Start-->
<%#= render 'ecofnb/about_us' %>
<!--About Section END-->
<!-- FEATURE START -->
<%= render 'ecofnb/feature' %>

<!-- FEATURE END -->
<%#= render 'ecofnb/slider' %>

<!-- <br><br> -->
<!--Review Slider Start-->
<%= render 'ecofnb/reviewslider' %>
<!--Review Slider End-->

app/views/ecofnb/stay_category.html.erb
<!-- Page Banner -->
<div class="container-fluid no-left-padding no-right-padding page-banner gallery-masonry-banner">
    <!-- Container -->
    <div class="container">
        <h3 class="tc_white"><%= @stay_category.try(:name)%></h3>
        
    </div><!-- Container /- -->
</div><!-- Page Banner /- -->

<main class="site-main">
    <% if flash[:alert] %>
     <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <!-- Gallery Masonry -->
    <div class="container-fluid no-left-padding no-right-padding gallery-main gallery-masonry">
        <!-- Container -->
        <div class="container">
        </div><!-- Container /- -->
        <!-- Gallery List -->
        <div class="row gallery-list">
          <%@homestays.each do |homestay|%> 
            <div class="col-md-3 col-sm-4 col-xs-6 gallery-box environment">
                <div class="gallery-content">
                    <i><a href="<%= stay_path(homestay)%>"><img src="<%= homestay.image_select%>" alt="vista" /></a></i>
                    <div class="gallery-detail">
                        <!-- <a class="zoom" href="<%= homestay.image_select%>"><i class="fa fa-picture-o fa-5x"></i></a> -->
                        <a href="<%=stay_path(homestay)%>"><i class="fa fa-link"></i></a>
                    </div>
                    <!-- <div class="homestay-title"> -->
                      <h5><a class="homestay-title" href="<%=stay_path(homestay)%>"><%= homestay.stay_name %>&nbsp;&nbsp;<%= homestay.stay_title %></a></h5>
                      <!-- <p class="homestay-title"><%#= homestay.address %></p> -->
                    <!-- </div> -->
                </div>
            </div>
          <%end%>
        </div><!-- Gallery List /- -->
        <div class="clearfix"></div>
    </div><!-- Gallery Masonry /- -->
    </main>
<style type="text/css">
    .gallery-content img {
    width: 100%;
    float: left;
    height: 190px;
    min-height: 190px;
}

</style>